name: Update & crop subway strips daily
on:
  schedule:
    - cron: '0 3 * * *'          # 每天 UTC 03:00
  workflow_dispatch:

jobs:
  fetch-crop-push:
    runs-on: ubuntu-latest

    env:
      MAP_DIR: assets/maps
      TARGET_SIZE: 1200x300
      LONDON_URL:  https://content.tfl.gov.uk/london-rail-and-tube-services-map.pdf
      TOKYO_URL:   https://www.pasmo.co.jp/area/train/all.pdf
      BEIJING_URL: https://imgbdb4.bendibao.com/bjbdb/202412/13/20241213172847_31099.jpg

    steps:
      # ① 检出仓库（改成多行写法）
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.METRICS_TOKEN }}

      # ② 安装依赖
      - name: Install deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ghostscript imagemagick curl

      # ③ 下载三张源图
      - name: Download originals
        run: |
          mkdir -p $MAP_DIR/original
          curl -L -o $MAP_DIR/original/london.pdf   "$LONDON_URL"
          curl -L -o $MAP_DIR/original/tokyo.pdf    "$TOKYO_URL"
          curl -L -o $MAP_DIR/original/beijing.jpg  "$BEIJING_URL"

      # ④ 裁剪 ➜ 统一尺寸
      - name: Crop centre strips
        run: |
          mkdir -p $MAP_DIR/cropped
          # ★ 请替换为你真实测量的 WxH+X+Y ★
          # London
          gs -q -sDEVICE=pngalpha -r300 -o /tmp/london.png "$MAP_DIR/original/london.pdf"
          convert /tmp/london.png \
                  -crop 2209x553+1088+1003 +repage \
                  -background white -alpha remove -alpha off \
                  -resize "$TARGET_SIZE!" -strip \
                  "$MAP_DIR/cropped/london-centre.png"
          
          # Beijing（原 JPG，无透明，不用改）
          convert "$MAP_DIR/original/beijing.jpg" \
                  -crop 1850x463+352+753 +repage \
                  -resize "$TARGET_SIZE!" -strip \
                  "$MAP_DIR/cropped/beijing-centre.png"
          
          # Tokyo
          gs -q -sDEVICE=pngalpha -r300 -o /tmp/tokyo.png "$MAP_DIR/original/tokyo.pdf"
          convert /tmp/tokyo.png \
                  -crop 3217x805+273+884 +repage \
                  -background white -alpha remove -alpha off \
                  -resize "$TARGET_SIZE!" -strip \
                  "$MAP_DIR/cropped/tokyo-centre.png"


      # ⑤ 把三种日期写回 README（保持不变）
      - name: Update README dates
        run: |
          Y=$(date +%Y); M=$(date +%-m); D=$(date +%-d)
          EN="${Y}-$(printf '%02d' $M)-$(printf '%02d' $D)"
          CN="${Y}年${M}月${D}日"
          ERA=$((Y-2018)); JP="令和${ERA}年${M}月${D}日"

          sed -i -E "s|(<!--MAP_UPDATE_DATE_EN-->).*?(<!--/MAP_UPDATE_DATE_EN-->)|\1${EN}\2|" README.md
          sed -i -E "s|(<!--MAP_UPDATE_DATE_CN-->).*?(<!--/MAP_UPDATE_DATE_CN-->)|\1${CN}\2|" README.md
          sed -i -E "s|(<!--MAP_UPDATE_DATE_JP-->).*?(<!--/MAP_UPDATE_DATE_JP-->)|\1${JP}\2|" README.md

      # ⑥ 仅在有变化时提交
      - name: Commit & push if changed
        run: |
          git config user.name  github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add assets/maps/cropped/* README.md
          git diff --cached --quiet || {
            git commit -m "chore: subway strips & date update $(date +'%F')"
            git push
          }
